import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { startOfDay, endOfDay, subDays, isSameDay } from "date-fns";

export async function GET(req: Request) {
    // Security check for Cron (optional)
    const authHeader = req.headers.get("authorization");
    if (process.env.NODE_ENV === "production" && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
        return new Response("Unauthorized", { status: 401 });
    }

    try {
        const now = new Date();
        const today = startOfDay(now);

        // 1. Fetch active categories with fixedAmount
        const categories = await prisma.category.findMany({
            where: {
                isActive: true,
                fixedAmount: { not: null },
            },
            include: {
                recurringState: true,
            },
        });

        const results = [];

        for (const category of categories) {
            let shouldGenerate = false;
            const lastGenerated = category.recurringState?.lastGeneratedDate;

            if (category.frequency === "DAILY") {
                if (!lastGenerated || !isSameDay(lastGenerated, today)) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "WEEKDAYS") {
                const day = now.getDay();
                const isWeekday = day >= 1 && day <= 5;
                if (isWeekday && (!lastGenerated || !isSameDay(lastGenerated, today))) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "WEEKLY") {
                if (!lastGenerated || today.getTime() - lastGenerated.getTime() >= 7 * 24 * 60 * 60 * 1000) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "CUSTOM" && category.specificDays.length > 0) {
                const day = now.getDay();
                if (category.specificDays.includes(day) && (!lastGenerated || !isSameDay(lastGenerated, today))) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "MONTHLY") {
                if (!lastGenerated || today.getMonth() !== lastGenerated.getMonth() || today.getFullYear() !== lastGenerated.getFullYear()) {
                    shouldGenerate = true;
                }
            }

            if (shouldGenerate && category.fixedAmount) {
                // Create expense
                const expense = await prisma.expense.create({
                    data: {
                        userId: category.userId,
                        categoryId: category.id,
                        amount: category.fixedAmount,
                        date: today,
                        isAutoGenerated: true,
                        description: `Auto-generated: ${category.name}`,
                    },
                });

                // Update state
                await prisma.recurringState.upsert({
                    where: { categoryId: category.id },
                    update: { lastGeneratedDate: today },
                    create: {
                        categoryId: category.id,
                        lastGeneratedDate: today,
                    },
                });

                results.push({ category: category.name, amount: category.fixedAmount });
            }
        }

        return NextResponse.json({ success: true, processed: results.length, data: results });
    } catch (error: any) {
        console.error("Cron Error:", error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
