"use server";

import prisma from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";

export async function getExpenses() {
    const { userId } = auth();
    if (!userId) return [];

    return prisma.expense.findMany({
        where: { userId },
        include: { category: true },
        orderBy: { date: "desc" },
    });
}

export async function createExpense(data: {
    categoryId: string;
    amount: number;
    date?: string;
    description?: string;
    isAutoGenerated?: boolean;
}) {
    const { userId } = auth();
    if (!userId) throw new Error("Unauthorized");

    const expense = await prisma.expense.create({
        data: {
            userId,
            categoryId: data.categoryId,
            amount: data.amount,
            date: data.date ? new Date(data.date) : new Date(),
            description: data.description,
            isAutoGenerated: data.isAutoGenerated || false,
        },
    });

    revalidatePath("/expenses");
    revalidatePath("/dashboard");
    return expense;
}

export async function updateExpense(id: string, data: any) {
    const { userId } = auth();
    if (!userId) throw new Error("Unauthorized");

    const expense = await prisma.expense.update({
        where: { id, userId },
        data: {
            ...data,
            date: data.date ? new Date(data.date) : undefined,
        },
    });

    revalidatePath("/expenses");
    revalidatePath("/dashboard");
    return expense;
}

export async function deleteExpense(id: string) {
    const { userId } = auth();
    if (!userId) throw new Error("Unauthorized");

    await prisma.expense.delete({
        where: { id, userId },
    });

    revalidatePath("/expenses");
    revalidatePath("/dashboard");
}

export async function toggleCategoryExpense(categoryId: string, date: Date) {
    const { userId } = auth();
    if (!userId) throw new Error("Unauthorized");

    const start = new Date(date);
    start.setHours(0, 0, 0, 0);
    const end = new Date(date);
    end.setHours(23, 59, 59, 999);

    const existing = await prisma.expense.findFirst({
        where: {
            userId,
            categoryId,
            date: {
                gte: start,
                lte: end,
            },
        },
    });

    if (existing) {
        await prisma.expense.delete({
            where: { id: existing.id },
        });
    } else {
        const category = await prisma.category.findUnique({
            where: { id: categoryId },
        });

        if (!category || !category.fixedAmount) {
            throw new Error("Category not found or has no fixed amount");
        }

        await prisma.expense.create({
            data: {
                userId,
                categoryId,
                amount: category.fixedAmount,
                date: start,
                description: `Manual entry: ${category.name}`,
                isAutoGenerated: false,
            },
        });
    }

    revalidatePath("/expenses");
    revalidatePath("/dashboard");
}
