"use server";

import prisma from "@/lib/prisma";
import { startOfDay, isSameDay, set } from "date-fns";
import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { sendPushNotification } from "./notifications";

export async function syncRecurringEntries() {
    const { userId } = auth();
    if (!userId) return { success: false, error: "Unauthorized" };

    try {
        const userSettings = await prisma.user.findUnique({
            where: { clerkId: userId },
            select: { recurringSyncTime: true }
        });
        const syncTime = userSettings?.recurringSyncTime || "00:00";
        const [syncHours, syncMinutes] = syncTime.split(":").map(Number);

        const now = new Date();
        const today = startOfDay(now);

        // Fetch active recurring categories for this user
        const categories = await prisma.category.findMany({
            where: {
                userId,
                isActive: true,
                isRecurring: true,
                fixedAmount: { not: null },
                trackingMode: "CALENDAR",
            },
            include: {
                recurringState: true,
            },
        });

        const generated = [];

        for (const category of categories) {
            let shouldGenerate = false;
            const lastGenerated = category.recurringState?.lastGeneratedDate;

            if (category.frequency === "DAILY") {
                if (!lastGenerated || !isSameDay(lastGenerated, today)) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "WEEKDAYS") {
                const day = now.getDay();
                const isWeekday = day >= 1 && day <= 5;
                if (isWeekday && (!lastGenerated || !isSameDay(lastGenerated, today))) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "WEEKLY") {
                // Check if it's been N weeks since last generated
                if (!lastGenerated) {
                    shouldGenerate = true;
                } else {
                    const diffDays = Math.floor((today.getTime() - lastGenerated.getTime()) / (1000 * 60 * 60 * 24));
                    if (diffDays >= (category.intervalCount || 1) * 7) {
                        shouldGenerate = true;
                    }
                }
            } else if (category.frequency === "CUSTOM" && category.specificDays.length > 0) {
                const day = now.getDay();
                if (category.specificDays.includes(day) && (!lastGenerated || !isSameDay(lastGenerated, today))) {
                    shouldGenerate = true;
                }
            } else if (category.frequency === "MONTHLY") {
                if (!lastGenerated) {
                    shouldGenerate = true;
                } else {
                    const monthDiff = (today.getFullYear() - lastGenerated.getFullYear()) * 12 + (today.getMonth() - lastGenerated.getMonth());
                    if (monthDiff >= (category.intervalCount || 1)) {
                        shouldGenerate = true;
                    }
                }
            }

            if (shouldGenerate && category.fixedAmount) {
                // Apply user custom time
                const generationDate = set(today, { hours: syncHours, minutes: syncMinutes });

                // Create expense
                await prisma.expense.create({
                    data: {
                        userId: category.userId,
                        categoryId: category.id,
                        amount: category.fixedAmount,
                        date: generationDate,
                        isAutoGenerated: true,
                        description: `Auto-generated: ${category.name}`,
                    },
                });

                // Update recurring state
                await prisma.recurringState.upsert({
                    where: { categoryId: category.id },
                    update: { lastGeneratedDate: today },
                    create: {
                        categoryId: category.id,
                        lastGeneratedDate: today,
                    },
                });

                generated.push(category.name);
            }
        }

        if (generated.length > 0) {
            revalidatePath("/dashboard");
            revalidatePath("/categories");

            // Send real push notification
            await sendPushNotification(
                userId,
                "Recurring Entries Marked 🤖",
                `Automatically marked: ${generated.join(", ")}`,
                "/dashboard"
            );
        }

        return {
            success: true,
            generatedCount: generated.length,
            categories: generated
        };
    } catch (error: any) {
        console.error("Sync Recurring Entries Error:", error);
        return { success: false, error: error.message, generatedCount: 0, categories: [] };
    }
}
